DROP SCHEMA PUBLIC CASCADE;
CREATE SCHEMA PUBLIC;

-- contendra la lista de marcas

CREATE TABLE TRADEMARKS
(
	ID_TRADEMARK BIGSERIAL NOT NULL,
	NAME_TRADEMARK VARCHAR (255) NOT NULL,
	PRIMARY KEY (ID_TRADEMARK),
	DELETE_TIMETAMP TIMESTAMP NULL
);

-- contendra a lista de categorias

CREATE TABLE CATEGORIES
(
	ID_CATEGORY BIGSERIAL NOT NULL,
	NAME_CATEGORY VARCHAR (255) NOT NULL,
	PRIMARY KEY (ID_CATEGORY),
	DELETE_TIMETAMP TIMESTAMP NULL
);

-- listado de productos en general
-- el precio del productos sera el valor de venta de la unidad

CREATE TABLE PRODUCTS
(
	ID_PRODUCT BIGSERIAL NOT NULL,
	UID_PRODUCT VARCHAR(255) NOT NULL UNIQUE,
	BARCODE_PRODUCT VARCHAR (255) NOT NULL,
	IMG_PRODUCT VARCHAR(255) NOT NULL,
	NAME_PRODUCT VARCHAR (255) NOT NULL,
	DESCRIPTION_PRODUCT text NOT NULL,
	ID_TRADEMARK INT NOT NULL,
	FOREIGN KEY (ID_TRADEMARK) REFERENCES TRADEMARKS (ID_TRADEMARK),
	ID_CATEGORY INT NOT NULL,
	FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORIES (ID_CATEGORY),
	PRICE_PRODUCT NUMERIC (9,4) NOT NULL,
	STOCK int NOT NULL,
	MIN_PURCHASE int NOT NULL,
	DISCOUNT_PRODUCT int NOT NULL,
	STATE_PRODUCT VARCHAR (255) NOT NULL,
	UID_SUPPLIER CHAR(36) NOT NULL,
	PRIMARY KEY (ID_PRODUCT),
	DELETE_TIMETAMP TIMESTAMP NULL
);

-- contiene la informacion nesecaria par establecer un pedidio a un cliente

CREATE TABLE ORDERS
(
	ID_ORDER BIGSERIAL NOT NULL,
	UID_ORDER VARCHAR (255) NOT NULL,
	UID_SUPPLIER CHAR(36) NOT NULL,
	UID_CLIENT VARCHAR (255) NOT NULL,
	DATE_ORDER TIMESTAMP NOT NULL,
	DATE_DELIVERY DATE NOT NULL,
	SUB_TOTAL NUMERIC (9, 4) NULL,
	SURCHARGE NUMERIC (9, 4) NULL,
	TOTAL NUMERIC (9, 4) NULL,
	STATE_ORDER VARCHAR (255) NOT NULL,
	PRIMARY KEY (ID_ORDER),
	DELETE_TIMETAMP TIMESTAMP NULL,
	UPDATE_TIMETAMP TIMESTAMP NULL
);

-- lista todos los productos solicitados por el cleinte
-- las promosiones seran aplicadas "automaticamente"

CREATE TABLE DETAIL_ORDERS
(
	ID_DETAIL BIGSERIAL NOT NULL,
	ID_ORDER INT NOT NULL,
	FOREIGN KEY (ID_ORDER) REFERENCES ORDERS (ID_ORDER),
	ID_PRODUCT INT NOT NULL,
	FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT),
	PRICE_PRODUCT NUMERIC (9,4) NOT NULL,
	QUANTITY INT NOT NULL,
	DISCOUNT_PRODUCT int NOT NULL,
	PRIMARY KEY (ID_DETAIL)
);